const ActionTypes = {
    ADD_TASK: 'ADD_TASK',
    TASKS_FETCH_START: 'TASKS_FETCH_START',
    TASKS_FETCH_COMPLETE: 'TASKS_FETCH_COMPLETE',
    TASKS_FETCH_ERROR: 'TASKS_FETCH_ERROR',
    TASK_FETCH_START: 'TASK_FETCH_START',
    TASK_FETCH_COMPLETE: 'TASK_FETCH_COMPLETE',
    TASK_FETCH_ERROR: 'TASK_FETCH_ERROR'
};

export default ActionTypes;
